version: '3.0'

services:

  db:
    image: postgres:15.2
    container_name: datalabDB
    restart: always
    volumes:
      - ./db/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=datalabDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=io
    ports:
      - "5432:5432"